name: Auto Generate AI Summaries

on:
  # Triggered when new email arrives via webhook
  repository_dispatch:
    types: [new-email]
  
  # Backup: Runs on a custom schedule (in case webhook fails)
  schedule:
    - cron: '0 5,8,11,14,21 * * *'  # 8am, 11am, 2pm, 5pm, midnight Israel time (summer)

jobs:
  trigger-ai-function:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger AI Summary Generation
        run: |
          echo "🤖 Triggering AI summary generation..."
          echo "Event: ${{ github.event_name }}"
          
          response=$(curl -s -X POST \
            -H "X-API-Key: ${{ secrets.AUTO_AI_SECRET_KEY }}" \
            "https://hanahotplus-jlm.base44.app/functions/autoGenerateAISummariesMake")
          
          echo "📊 Response:"
          echo "$response"
          
      - name: Complete
        run: echo "✅ Function execution completed"
